apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "rolloutdemo.fullname" . }}
  labels:
    app: {{ template "rolloutdemo.name" . }}
    chart: {{ template "rolloutdemo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "rolloutdemo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rolloutdemo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}

  {{- if .Values.rollout.strategy.canary.true }}
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        clusterScope: true
        startingStep: 2
        args:
        - name: namespace
          value: {{ .Release.Namespace }}
        - name: route-name
          value: {{ template "rolloutdemo.fullname" . }}-stable-{{ .Release.Namespace }}
        - name: route-url
          value: {{ include "rolloutdemo.activeRouteHost" . }}
        - name: api-token
          valueFrom:
            secretKeyRef:
              name: monitor-auth-secret
              key: token
      canaryService: {{ template "rolloutdemo.fullname" . }}-canary-{{ .Release.Namespace }}
      stableService: {{ template "rolloutdemo.fullname" . }}-stable-{{ .Release.Namespace }}
      trafficRouting:
        plugins:
          argoproj-labs/openshift:
            routes:
              - {{ template "rolloutdemo.fullname" . }}-stable-{{ .Release.Namespace }}
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
        - setWeight: 40
        - pause: {duration: 30s}
        - setWeight: 60
        - pause: {duration: 60s}
  {{- end }}


    successfulRunHistoryLimit: 2
    unsuccessfulRunHistoryLimit: 1
